version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: dotnet build -c Release

deploy:
  - provider: NuGet
    api_key:
      secure: N9x9UJIdLIEFjil5aTu15Km5bVmC9D5TCnSH61bh/xn+uAo9QWUr8ixqWZfRkand
    on:
      appveyor_repo_tag: true
